//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CheckingServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/Checking")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.CheckingServiceRef.Credit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.CheckingServiceRef.Debit))]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credit", Namespace="http://schemas.datacontract.org/2004/07/Checking")]
    [System.SerializableAttribute()]
    public partial class Credit : Client.CheckingServiceRef.Transaction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.CheckingServiceRef.CreditTypeEnum CreditTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.CheckingServiceRef.CreditTypeEnum CreditType {
            get {
                return this.CreditTypeField;
            }
            set {
                if ((this.CreditTypeField.Equals(value) != true)) {
                    this.CreditTypeField = value;
                    this.RaisePropertyChanged("CreditType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Debit", Namespace="http://schemas.datacontract.org/2004/07/Checking")]
    [System.SerializableAttribute()]
    public partial class Debit : Client.CheckingServiceRef.Transaction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CheckNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.CheckingServiceRef.DebitTypeEnum DebitTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FeeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CheckNo {
            get {
                return this.CheckNoField;
            }
            set {
                if ((this.CheckNoField.Equals(value) != true)) {
                    this.CheckNoField = value;
                    this.RaisePropertyChanged("CheckNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.CheckingServiceRef.DebitTypeEnum DebitType {
            get {
                return this.DebitTypeField;
            }
            set {
                if ((this.DebitTypeField.Equals(value) != true)) {
                    this.DebitTypeField = value;
                    this.RaisePropertyChanged("DebitType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebitTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/Checking")]
    public enum DebitTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Check = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cash = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATM = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/Checking")]
    public enum CreditTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Check = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cash = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoneyOrder = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wire = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TransactionList", Namespace="http://schemas.datacontract.org/2004/07/Checking", ItemName="Transaction")]
    [System.SerializableAttribute()]
    public class TransactionList : System.Collections.Generic.List<Client.CheckingServiceRef.Transaction> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckingServiceRef.ICheckingService")]
    public interface ICheckingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/AddDebit", ReplyAction="http://tempuri.org/ICheckingService/AddDebitResponse")]
        void AddDebit(Client.CheckingServiceRef.Debit debit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/AddDebit", ReplyAction="http://tempuri.org/ICheckingService/AddDebitResponse")]
        System.Threading.Tasks.Task AddDebitAsync(Client.CheckingServiceRef.Debit debit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/AddCredit", ReplyAction="http://tempuri.org/ICheckingService/AddCreditResponse")]
        void AddCredit(Client.CheckingServiceRef.Credit credit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/AddCredit", ReplyAction="http://tempuri.org/ICheckingService/AddCreditResponse")]
        System.Threading.Tasks.Task AddCreditAsync(Client.CheckingServiceRef.Credit credit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/GetAllTransactions", ReplyAction="http://tempuri.org/ICheckingService/GetAllTransactionsResponse")]
        Client.CheckingServiceRef.TransactionList GetAllTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/GetAllTransactions", ReplyAction="http://tempuri.org/ICheckingService/GetAllTransactionsResponse")]
        System.Threading.Tasks.Task<Client.CheckingServiceRef.TransactionList> GetAllTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/GetTransactionsByDateRange", ReplyAction="http://tempuri.org/ICheckingService/GetTransactionsByDateRangeResponse")]
        Client.CheckingServiceRef.TransactionList GetTransactionsByDateRange(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/GetTransactionsByDateRange", ReplyAction="http://tempuri.org/ICheckingService/GetTransactionsByDateRangeResponse")]
        System.Threading.Tasks.Task<Client.CheckingServiceRef.TransactionList> GetTransactionsByDateRangeAsync(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/GetCreditsByType", ReplyAction="http://tempuri.org/ICheckingService/GetCreditsByTypeResponse")]
        Client.CheckingServiceRef.TransactionList GetCreditsByType(Client.CheckingServiceRef.CreditTypeEnum creditType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/GetCreditsByType", ReplyAction="http://tempuri.org/ICheckingService/GetCreditsByTypeResponse")]
        System.Threading.Tasks.Task<Client.CheckingServiceRef.TransactionList> GetCreditsByTypeAsync(Client.CheckingServiceRef.CreditTypeEnum creditType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/GetDebitsByType", ReplyAction="http://tempuri.org/ICheckingService/GetDebitsByTypeResponse")]
        Client.CheckingServiceRef.TransactionList GetDebitsByType(Client.CheckingServiceRef.DebitTypeEnum debitType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckingService/GetDebitsByType", ReplyAction="http://tempuri.org/ICheckingService/GetDebitsByTypeResponse")]
        System.Threading.Tasks.Task<Client.CheckingServiceRef.TransactionList> GetDebitsByTypeAsync(Client.CheckingServiceRef.DebitTypeEnum debitType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckingServiceChannel : Client.CheckingServiceRef.ICheckingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckingServiceClient : System.ServiceModel.ClientBase<Client.CheckingServiceRef.ICheckingService>, Client.CheckingServiceRef.ICheckingService {
        
        public CheckingServiceClient() {
        }
        
        public CheckingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddDebit(Client.CheckingServiceRef.Debit debit) {
            base.Channel.AddDebit(debit);
        }
        
        public System.Threading.Tasks.Task AddDebitAsync(Client.CheckingServiceRef.Debit debit) {
            return base.Channel.AddDebitAsync(debit);
        }
        
        public void AddCredit(Client.CheckingServiceRef.Credit credit) {
            base.Channel.AddCredit(credit);
        }
        
        public System.Threading.Tasks.Task AddCreditAsync(Client.CheckingServiceRef.Credit credit) {
            return base.Channel.AddCreditAsync(credit);
        }
        
        public Client.CheckingServiceRef.TransactionList GetAllTransactions() {
            return base.Channel.GetAllTransactions();
        }
        
        public System.Threading.Tasks.Task<Client.CheckingServiceRef.TransactionList> GetAllTransactionsAsync() {
            return base.Channel.GetAllTransactionsAsync();
        }
        
        public Client.CheckingServiceRef.TransactionList GetTransactionsByDateRange(System.DateTime start, System.DateTime end) {
            return base.Channel.GetTransactionsByDateRange(start, end);
        }
        
        public System.Threading.Tasks.Task<Client.CheckingServiceRef.TransactionList> GetTransactionsByDateRangeAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetTransactionsByDateRangeAsync(start, end);
        }
        
        public Client.CheckingServiceRef.TransactionList GetCreditsByType(Client.CheckingServiceRef.CreditTypeEnum creditType) {
            return base.Channel.GetCreditsByType(creditType);
        }
        
        public System.Threading.Tasks.Task<Client.CheckingServiceRef.TransactionList> GetCreditsByTypeAsync(Client.CheckingServiceRef.CreditTypeEnum creditType) {
            return base.Channel.GetCreditsByTypeAsync(creditType);
        }
        
        public Client.CheckingServiceRef.TransactionList GetDebitsByType(Client.CheckingServiceRef.DebitTypeEnum debitType) {
            return base.Channel.GetDebitsByType(debitType);
        }
        
        public System.Threading.Tasks.Task<Client.CheckingServiceRef.TransactionList> GetDebitsByTypeAsync(Client.CheckingServiceRef.DebitTypeEnum debitType) {
            return base.Channel.GetDebitsByTypeAsync(debitType);
        }
    }
}
